### ISSUE TITLE
Cannot register a model if there's a non-managed model referring to it

### ISSUE THREAD

**Issue by aqeelat** [jazzband/django-auditlog#315]
I have these two models, which have worked for me for many months.

```python
class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=250, blank=True)
    email = models.CharField(max_length=100, unique=True, blank=True, null=True)

class UserOrdersView(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.DO_NOTHING,
        related_name='user_orders',
        primary_key=True
    )
    # other fields
    class Meta:
        managed = False
        db_table = "users_userordersview"
```

However, when I register the User class, my testcases fail, with the following stack:
```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/db/models/fields/related_descriptors.py", line 393, in __get__
    rel_obj = self.related.get_cached_value(instance)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/db/models/fields/mixins.py", line 13, in get_cached_value
    return instance._state.fields_cache[cache_name]
KeyError: 'user_orders'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "users_userordersview" does not exist
LINE 1: ...", "users_userordersview"."churned_date" FROM "users_use...
```

I tried completely removing the view from my app (including the migrations), migrating to a clean database, and registering the user mode, and it worked fine.

Why does auditlog care about the view? The view is not registered. (ironically, I tried registering it and the tests passed).

**Comment by hramezani** [comment]
Sorry @aqeelat for the late response.

Do you still have this problem?

**Comment by aqeelat** [comment]
@hramezani Yes. I fixed it by using:
```
for app_label in internal_apps_list:
    for model in apps.get_app_config(app_label.split(".")[-1]).get_models(include_auto_created=True):
        meta = model._meta
        if not meta.managed:
            continue

        m2m_fields = [m for m in meta.fields if isinstance(m, models.ManyToManyField)]

        exclude_fields = [
            i.related_name for i in meta.related_objects if i.related_name and not i.related_model._meta.managed
        ]

        auditlog.register(model, exclude_fields=exclude_fields, m2m_fields=m2m_fields)
```

This is related to #548

**Comment by hramezani** [comment]
@aqeelat do you want to create a PR?

**Comment by aqeelat** [comment]
@hramezani sure
