### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 594: ordinal not in range(128)

### ISSUE THREAD

**Issue by charleswhchan** [jazzband/django-auditlog#327]
When I use `pip download django-auditlog==1.0a1`, I get the following error

```
Collecting django-auditlog==1.0a1
  Downloading django-auditlog-1.0a1.tar.gz (15 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/virtualenv/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-download-_2nasxwx/django-auditlog_afb0edccde204fa5a20c7885b5551294/setup.py'"'"'; __file__='"'"'/tmp/pip-download-_2nasxwx/django-auditlog_afb0edccde204fa5a20c7885b5551294/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-e5a7sfrx
         cwd: /tmp/pip-download-_2nasxwx/django-auditlog_afb0edccde204fa5a20c7885b5551294/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-download-_2nasxwx/django-auditlog_afb0edccde204fa5a20c7885b5551294/setup.py", line 9, in <module>
        long_description = readme_file.read()
      File "/tmp/virtualenv/lib64/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 594: ordinal not in range(128)
    ----------------------------------------
```

OS: Linux
Python: 3.6.9
pip: 21.0.1
setuptools: 54.1.2

**Comment by Linkid** [comment]
Hi. I can't reproduce this bug. Maybe you should check your `LANG` and `PYTHONIOENCODING` environment variables.
