### ISSUE TITLE
TypeError with django-import-export

### ISSUE THREAD

**Issue by stupid-hammer** [jazzband/django-auditlog#360]
Hi, thank you for providing so awsome software to log all user actions in django. but i met a problem, when i import data in django admin contral panel, auditlog receivers line 19 json.dumps() raise a error :

```
[2022-02-28 15:33:54,283] [log.py:228] [ERROR]- Internal Server Error: /admin/covid19/food/process_import/
Traceback (most recent call last):
  File "/Users/qinfei/PycharmProjects/precision/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/qinfei/PycharmProjects/precision/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/qinfei/PycharmProjects/precision/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/qinfei/PycharmProjects/precision/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/qinfei/PycharmProjects/precision/venv/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/qinfei/PycharmProjects/precision/venv/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 231, in inner
    return view(request, *args, **kwargs)
  File "/Users/qinfei/PycharmProjects/precision/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/qinfei/PycharmProjects/precision/venv/lib/python3.7/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/Users/qinfei/PycharmProjects/precision/venv/lib/python3.7/site-packages/import_export/admin.py", line 153, in process_import
    return self.process_result(result, request)
  File "/Users/qinfei/PycharmProjects/precision/venv/lib/python3.7/site-packages/import_export/admin.py", line 169, in process_result
    self.generate_log_entries(result, request)
  File "/Users/qinfei/PycharmProjects/precision/venv/lib/python3.7/site-packages/import_export/admin.py", line 194, in generate_log_entries
    change_message=_("%s through import_export" % row.import_type),
  File "/Users/qinfei/PycharmProjects/precision/venv/lib/python3.7/site-packages/django/contrib/admin/models.py", line 35, in log_action
    change_message=change_message,
  File "/Users/qinfei/PycharmProjects/precision/venv/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/qinfei/PycharmProjects/precision/venv/lib/python3.7/site-packages/django/db/models/query.py", line 433, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/qinfei/PycharmProjects/precision/venv/lib/python3.7/site-packages/django/db/models/base.py", line 746, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/qinfei/PycharmProjects/precision/venv/lib/python3.7/site-packages/django/db/models/base.py", line 795, in save_base
    update_fields=update_fields, raw=raw, using=using,
  File "/Users/qinfei/PycharmProjects/precision/venv/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/Users/qinfei/PycharmProjects/precision/venv/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/Users/qinfei/PycharmProjects/precision/venv/lib/python3.7/site-packages/auditlog/receivers.py", line 19, in log_create
    changes=json.dumps(changes),
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type __proxy__ is not JSON serializable
```

my requirements.txt version is:

```
Django==3.0.7
django-admin-rangefilter==0.6.1
django-import-export==2.2.0
django-auditlog==1.0.0
......
```

thanks for your patient!

**Comment by hramezani** [comment]
Thanks @stupid-hammer for reporting and sorry for the late response.

Could you please provide more information like the data that you want to import
