### ISSUE TITLE
localtime() cannot be applied to a naive datetime

### ISSUE THREAD

**Issue by k4rimi** [jazzband/django-auditlog#480]
My Project is using the setting USE_TZ=False and it is throwing the following error when i open audit log admin:

<img width="924" alt="Screen Shot 2022-12-18 at 6 02 09 PM" src="https://user-images.githubusercontent.com/69834379/208304116-c380c52a-8b63-49c7-8078-8bc1e8f2dca8.png">

`During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "/Users/shayan/Desktop/Projects/firefly/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/shayan/Desktop/Projects/firefly/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/Users/shayan/Desktop/Projects/firefly/venv/lib/python3.8/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/Users/shayan/Desktop/Projects/firefly/venv/lib/python3.8/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/Users/shayan/Desktop/Projects/firefly/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 62, in render
    return self.template.render(context)
  File "/Users/shayan/Desktop/Projects/firefly/venv/lib/python3.8/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/Users/shayan/Desktop/Projects/firefly/venv/lib/python3.8/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/shayan/Desktop/Projects/firefly/venv/lib/python3.8/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/shayan/Desktop/Projects/firefly/venv/lib/python3.8/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/shayan/Desktop/Projects/firefly/venv/lib/python3.8/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/Users/shayan/Desktop/Projects/firefly/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/Users/shayan/Desktop/Projects/firefly/venv/lib/python3.8/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/shayan/Desktop/Projects/firefly/venv/lib/python3.8/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/shayan/Desktop/Projects/firefly/venv/lib/python3.8/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/shayan/Desktop/Projects/firefly/venv/lib/python3.8/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/Users/shayan/Desktop/Projects/firefly/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/Users/shayan/Desktop/Projects/firefly/venv/lib/python3.8/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/shayan/Desktop/Projects/firefly/venv/lib/python3.8/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/shayan/Desktop/Projects/firefly/venv/lib/python3.8/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/shayan/Desktop/Projects/firefly/venv/lib/python3.8/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/Users/shayan/Desktop/Projects/firefly/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/Users/shayan/Desktop/Projects/firefly/venv/lib/python3.8/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/shayan/Desktop/Projects/firefly/venv/lib/python3.8/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/shayan/Desktop/Projects/firefly/venv/lib/python3.8/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/Users/shayan/Desktop/Projects/firefly/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/Users/shayan/Desktop/Projects/firefly/venv/lib/python3.8/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/shayan/Desktop/Projects/firefly/venv/lib/python3.8/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/shayan/Desktop/Projects/firefly/venv/lib/python3.8/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/Users/shayan/Desktop/Projects/firefly/venv/lib/python3.8/site-packages/django/contrib/admin/templatetags/base.py", line 45, in render
    return super().render(context)
  File "/Users/shayan/Desktop/Projects/firefly/venv/lib/python3.8/site-packages/django/template/library.py", line 260, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/Users/shayan/Desktop/Projects/firefly/venv/lib/python3.8/site-packages/django/contrib/admin/templatetags/admin_list.py", line 336, in result_list
    "results": list(results(cl)),
  File "/Users/shayan/Desktop/Projects/firefly/venv/lib/python3.8/site-packages/django/contrib/admin/templatetags/admin_list.py", line 312, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "/Users/shayan/Desktop/Projects/firefly/venv/lib/python3.8/site-packages/django/contrib/admin/templatetags/admin_list.py", line 303, in __init__
    super().__init__(*items)
  File "/Users/shayan/Desktop/Projects/firefly/venv/lib/python3.8/site-packages/django/contrib/admin/templatetags/admin_list.py", line 213, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "/Users/shayan/Desktop/Projects/firefly/venv/lib/python3.8/site-packages/django/contrib/admin/utils.py", line 280, in lookup_field
    value = attr(obj)
  File "/Users/shayan/Desktop/Projects/firefly/venv/lib/python3.8/site-packages/auditlog/mixins.py", line 23, in created
    return localtime(obj.timestamp)
  File "/Users/shayan/Desktop/Projects/firefly/venv/lib/python3.8/site-packages/django/utils/timezone.py", line 206, in localtime
    raise ValueError("localtime() cannot be applied to a naive datetime")
ValueError: localtime() cannot be applied to a naive datetime`
```

**Comment by hramezani** [comment]
Thanks @k4rimi for reporting this issue.

Here is the possible fix for the issue:

```
diff --git a/auditlog/mixins.py b/auditlog/mixins.py
index 84c18d0..7d393fd 100644
--- a/auditlog/mixins.py
+++ b/auditlog/mixins.py
@@ -6,7 +6,7 @@ from django.forms.utils import pretty_name
 from django.urls.exceptions import NoReverseMatch
 from django.utils.html import format_html, format_html_join
 from django.utils.safestring import mark_safe
-from django.utils.timezone import localtime
+from django.utils.timezone import localtime, is_aware
 from django.utils.translation import gettext_lazy as _
 
 from auditlog.models import LogEntry
@@ -19,7 +19,9 @@ MAX = 75
 class LogEntryAdminMixin:
     @admin.display(description=_("Created"))
     def created(self, obj):
-        return localtime(obj.timestamp)
+        if is_aware(obj.timestamp):
+            return localtime(obj.timestamp)
+        return obj.timestamp
 
     @admin.display(description=_("User"))
     def user_url(self, obj):
```

Would you like to prepare a patch with test and changelog for this issue?

**Comment by hramezani** [comment]
Fixed in https://github.com/jazzband/django-auditlog/commit/fcb6c4ce2716ff780c020ebce0b4cc6f3c103e65
