### ISSUE TITLE
backtrace from typo in app name

### ISSUE THREAD

**Issue by tykling** [jazzband/django-auditlog#491]
I got the following backtrace when I made a typo in an app name in `AUDITLOG_INCLUDE_TRACKING_MODELS`

```
 Traceback (most recent call last):
  File "/home/runner/work/rubberboot-admin-web/rubberboot-admin-web/code/src/manage.py", line 22, in <module>
    main()
  File "/home/runner/work/rubberboot-admin-web/rubberboot-admin-web/code/src/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/auditlog/apps.py", line 12, in ready
    auditlog.register_from_settings()
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/auditlog/registry.py", line 322, in register_from_settings
    self._register_models(settings.AUDITLOG_INCLUDE_TRACKING_MODELS)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/auditlog/registry.py", line 263, in _register_models
    model["model"] = self._get_model_classes(model["model"])[0]
```

The issue is in this line https://github.com/jazzband/django-auditlog/blob/ffa6d34b111d3ff84667a85b91fa48c4bfbb3471/auditlog/registry.py#L264 where it is assumed that a non-empty list is returned from `self._get_model_classes()` but that method can return an empty list in case of a `LookupError` exception.

I propose in case an unknown app is used in settings we either failing with a nicer error message, or skip the entry.

**Comment by alieh-rymasheuski** [comment]
Nicer error message please. Silent skips are dangerous.

**Comment by tykling** [comment]
OK :+1: I will create a PR this evening
