### ISSUE TITLE
localtime() cannot be applied to a naive datetime

### ISSUE THREAD

**Issue by DanielAlderman** [jazzband/django-auditlog#528]
Hello,

I am experiencing the same issue as #480.

Apparently this was fixed in https://github.com/jazzband/django-auditlog/commit/fcb6c4ce2716ff780c020ebce0b4cc6f3c103e65 but it still seems to be present for me.

I'm running 2.2.2, with USE_TZ=False.

Here is the traceback:

```
Environment:


Request Method: GET
Request URL: http://rapuklxdev05:8000/admin/auditlog/logentry/

Django Version: 4.1.7
Python Version: 3.10.2
Installed Applications:
['daphne',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.forms',
 'formtools',
 'auditlog',
 'crispy_forms',
 'crispy_bootstrap5',
 'channels',
 'toolmanager.apps.ToolmanagerConfig',
 'changejobowner.apps.ChangejobownerConfig',
 'tharsterndeliveryimporter.apps.TharsterndeliveryimporterConfig',
 'nonconformanceimporter.apps.NonconformanceimporterConfig',
 'dpdimporter.apps.DpdimporterConfig',
 'productiontracker.apps.ProductiontrackerConfig']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']


Template error:
In template /home/admin/.pyenv/versions/internaltools/lib/python3.10/site-packages/django/contrib/admin/templates/admin/change_list.html, error at line 68
   localtime() cannot be applied to a naive datetime
   58 :         {% block search %}{% search_form cl %}{% endblock %}
   59 :         {% block date_hierarchy %}{% if cl.date_hierarchy %}{% date_hierarchy cl %}{% endif %}{% endblock %}
   60 : 
   61 :         <form id="changelist-form" method="post"{% if cl.formset and cl.formset.is_multipart %} enctype="multipart/form-data"{% endif %} novalidate>{% csrf_token %}
   62 :         {% if cl.formset %}
   63 :           <div>{{ cl.formset.management_form }}</div>
   64 :         {% endif %}
   65 : 
   66 :         {% block result_list %}
   67 :           {% if action_form and actions_on_top and cl.show_admin_actions %}{% admin_actions %}{% endif %}
   68 :            {% result_list cl %} 
   69 :           {% if action_form and actions_on_bottom and cl.show_admin_actions %}{% admin_actions %}{% endif %}
   70 :         {% endblock %}
   71 :         {% block pagination %}{% pagination cl %}{% endblock %}
   72 :         </form>
   73 :       </div>
   74 :       {% block filters %}
   75 :         {% if cl.has_filters %}
   76 :           <div id="changelist-filter">
   77 :             <h2>{% translate 'Filter' %}</h2>
   78 :             {% if cl.has_active_filters %}<h3 id="changelist-filter-clear">


Traceback (most recent call last):
  File "/home/admin/.pyenv/versions/internaltools/lib/python3.10/site-packages/django/db/models/options.py", line 669, in get_field
    return self.fields_map[field_name]

During handling of the above exception ('created'), another exception occurred:
  File "/home/admin/.pyenv/versions/internaltools/lib/python3.10/site-packages/django/contrib/admin/utils.py", line 271, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "/home/admin/.pyenv/versions/internaltools/lib/python3.10/site-packages/django/contrib/admin/utils.py", line 302, in _get_non_gfk_field
    field = opts.get_field(name)
  File "/home/admin/.pyenv/versions/internaltools/lib/python3.10/site-packages/django/db/models/options.py", line 671, in get_field
    raise FieldDoesNotExist(

During handling of the above exception (LogEntry has no field named 'created'), another exception occurred:
  File "/home/admin/.pyenv/versions/internaltools/lib/python3.10/site-packages/asgiref/sync.py", line 486, in thread_handler
    raise exc_info[1]
  File "/home/admin/.pyenv/versions/internaltools/lib/python3.10/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = await get_response(request)
  File "/home/admin/.pyenv/versions/internaltools/lib/python3.10/site-packages/django/core/handlers/base.py", line 284, in _get_response_async
    response = await sync_to_async(
  File "/home/admin/.pyenv/versions/internaltools/lib/python3.10/site-packages/asgiref/sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/home/admin/.pyenv/versions/3.10.2/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
  File "/home/admin/.pyenv/versions/3.10.2/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/admin/.pyenv/versions/internaltools/lib/python3.10/site-packages/asgiref/sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
  File "/home/admin/.pyenv/versions/internaltools/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/admin/.pyenv/versions/internaltools/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/admin/.pyenv/versions/internaltools/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/admin/.pyenv/versions/internaltools/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/admin/.pyenv/versions/internaltools/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/admin/.pyenv/versions/internaltools/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/admin/.pyenv/versions/internaltools/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/admin/.pyenv/versions/internaltools/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/admin/.pyenv/versions/internaltools/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/admin/.pyenv/versions/internaltools/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/admin/.pyenv/versions/internaltools/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/admin/.pyenv/versions/internaltools/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/admin/.pyenv/versions/internaltools/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/admin/.pyenv/versions/internaltools/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/admin/.pyenv/versions/internaltools/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/admin/.pyenv/versions/internaltools/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/admin/.pyenv/versions/internaltools/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/admin/.pyenv/versions/internaltools/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/admin/.pyenv/versions/internaltools/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/admin/.pyenv/versions/internaltools/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/admin/.pyenv/versions/internaltools/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/admin/.pyenv/versions/internaltools/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/admin/.pyenv/versions/internaltools/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/admin/.pyenv/versions/internaltools/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/admin/.pyenv/versions/internaltools/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/admin/.pyenv/versions/internaltools/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/admin/.pyenv/versions/internaltools/lib/python3.10/site-packages/django/contrib/admin/templatetags/base.py", line 45, in render
    return super().render(context)
  File "/home/admin/.pyenv/versions/internaltools/lib/python3.10/site-packages/django/template/library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/home/admin/.pyenv/versions/internaltools/lib/python3.10/site-packages/django/contrib/admin/templatetags/admin_list.py", line 336, in result_list
    "results": list(results(cl)),
  File "/home/admin/.pyenv/versions/internaltools/lib/python3.10/site-packages/django/contrib/admin/templatetags/admin_list.py", line 312, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "/home/admin/.pyenv/versions/internaltools/lib/python3.10/site-packages/django/contrib/admin/templatetags/admin_list.py", line 303, in __init__
    super().__init__(*items)
  File "/home/admin/.pyenv/versions/internaltools/lib/python3.10/site-packages/django/contrib/admin/templatetags/admin_list.py", line 213, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "/home/admin/.pyenv/versions/internaltools/lib/python3.10/site-packages/django/contrib/admin/utils.py", line 280, in lookup_field
    value = attr(obj)
  File "/home/admin/.pyenv/versions/internaltools/lib/python3.10/site-packages/auditlog/mixins.py", line 23, in created
    return localtime(obj.timestamp)
  File "/home/admin/.pyenv/versions/internaltools/lib/python3.10/site-packages/django/utils/timezone.py", line 218, in localtime
    raise ValueError("localtime() cannot be applied to a naive datetime")

Exception Type: ValueError at /admin/auditlog/logentry/
Exception Value: localtime() cannot be applied to a naive datetime
```

**Comment by hramezani** [comment]
django-auditlog 2.3.0 just released.
You can find the fix there.
