### ISSUE TITLE
DateTimeField Cannot be set with Now()

### ISSUE THREAD

**Issue by dbready** [jazzband/django-auditlog#577]
Just found this package and it seems to do everything I need, but I encountered one small wrinkle that I wanted to share. My intention was to update a timestamp using Django [Now()](https://docs.djangoproject.com/en/dev/ref/models/database-functions/#now). Which is to say that the recorded timestamp should be from the perspective of the database, not my application server.

Defining a model like so

```python
from auditlog.registry import auditlog
from django.db import models

class Foo(models.Model):
	closed_dt = models.DateTimeField(null=True, blank=True)

auditlog.register(Foo)
```

If auditlog is not registered the below update function will work. However, when auditlog is registered to the model, I get a traceback because the timestamp is not the expected typed.

There is an easy enough bandaid solution of providing a datetime object instead, but it would be great if I could otherwise add auditlog without any required code changes.

```python
from django.db.models.functions import Now

def broken_update(request):
	foo = get_object_or_404(models.Foo, id=1)
	foo.closed_dt = Now()
	foo.save()
	return JsonResponse({"status":"ok"})
```

The traceback

```shell
Internal Server Error: /broken
Traceback (most recent call last):
  File "/home/thatguy/.cache/pypoetry/virtualenvs/django-audittest-gJainCZK-py3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/thatguy/.cache/pypoetry/virtualenvs/django-audittest-gJainCZK-py3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/thatguy/projects/sandbox/django_audittest/core/views.py", line 14, in broken_update
    foo.save()
  File "/home/thatguy/.cache/pypoetry/virtualenvs/django-audittest-gJainCZK-py3.10/lib/python3.10/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/home/thatguy/.cache/pypoetry/virtualenvs/django-audittest-gJainCZK-py3.10/lib/python3.10/site-packages/django/db/models/base.py", line 861, in save_base
    pre_save.send(
  File "/home/thatguy/.cache/pypoetry/virtualenvs/django-audittest-gJainCZK-py3.10/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/home/thatguy/.cache/pypoetry/virtualenvs/django-audittest-gJainCZK-py3.10/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/home/thatguy/.cache/pypoetry/virtualenvs/django-audittest-gJainCZK-py3.10/lib/python3.10/site-packages/auditlog/receivers.py", line 23, in wrapper
    signal_handler(*args, **kwargs)
  File "/home/thatguy/.cache/pypoetry/virtualenvs/django-audittest-gJainCZK-py3.10/lib/python3.10/site-packages/auditlog/receivers.py", line 60, in log_update
    changes = model_instance_diff(old, new, fields_to_check=update_fields)
  File "/home/thatguy/.cache/pypoetry/virtualenvs/django-audittest-gJainCZK-py3.10/lib/python3.10/site-packages/auditlog/diff.py", line 168, in model_instance_diff
    new_value = get_field_value(new, field)
  File "/home/thatguy/.cache/pypoetry/virtualenvs/django-audittest-gJainCZK-py3.10/lib/python3.10/site-packages/auditlog/diff.py", line 67, in get_field_value
    value = field.to_python(getattr(obj, field.name, None))
  File "/home/thatguy/.cache/pypoetry/virtualenvs/django-audittest-gJainCZK-py3.10/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 1546, in to_python
    parsed = parse_datetime(value)
  File "/home/thatguy/.cache/pypoetry/virtualenvs/django-audittest-gJainCZK-py3.10/lib/python3.10/site-packages/django/utils/dateparse.py", line 114, in parse_datetime
    return datetime.datetime.fromisoformat(value)
TypeError: fromisoformat: argument must be str
```

**Comment by hramezani** [comment]
@dbready Could you please install the beta version of the next major release  of django-auditlog by `pip install django-auditlog --pre` and test it? probably this problem has been fixed there.

**Comment by dbready** [comment]
Just tried with 3.0b2 and it still does not work.
